### ISSUE TITLE
Implementation Checklist for Solitaire Player Prototype

### ISSUE THREAD

**Issue by IBUSH001** [swisalps/Issues#12]
- [ ] Begin considering test cases: both failure and success
- [ ] Search for shuffles that will always result in failure
- [ ] Search for shuffles that will always result in success
- [ ] Create a minimal viable product for the solitaire simulator
