### ISSUE TITLE
Quality Assessment Checklist

### ISSUE THREAD

**Issue by slaufers001** [swisalps/Issues#25]
**Team Culture:**
- [x] Build team culture through non-work activities.
- [x] Regularly recognize and complement team members for their contributions.
- [x] Respectfully provide coaching to improve team effectiveness and efficiency.

**Communication:**
- [x] Set up and use communication tools and processes for effective and rapid information exchange.
https://drive.google.com/drive/folders/1BVM3hxEM8tmOFRsFiXiXBhVidSIeF-ue 
and through group text messaging (primarily)
- [x] Use these tools and processes regularly.
- [x] Establish and use remote communication tools and processes for distributed team interactions.
- [x] Establish and use initiation and exit checklists.
- [x] Establish and use team policy statement.

**Requirements and Analsys:**
- [x] Create user stories to capture basic product requirements.
https://docs.google.com/document/d/1tSBYS4YZr-WVV8qMVg2eYdDVU3uTBIOa9v0mA09F6yg/edit
- [x] Analyze, refine, prioritize, select and convert user stories into tasks for development.
https://github.com/orgs/swisalps/projects/2
- [ ] Organize tasks into Epic-story-task packages.
- [x] Experiment with Job Stories as an alternative to User Stories (see https://maherou.github.io/files/CS317/CS317-Links).

**Design:**
- [x] Created basic design documents such as class, interaction and use case.
https://drive.google.com/drive/folders/1BVM3hxEM8tmOFRsFiXiXBhVidSIeF-ue
- [x] Wrote lightweight design documents
https://docs.google.com/document/d/1mTA0SOsPmiM7arQO3vTMbfhNUfvmjsn92EGcFIBFMcI/edit
- [x] Wrote throw-away prototype code to explore high-risk design elements.
https://github.com/swisalps/Group_Work_General/branches

**Development:**
- [x] Create GitHub Isses describing major design and development tasks.
https://github.com/swisalps/Issues/issues
- [x] Establish GitHub Project (Kanban) board.
https://github.com/orgs/swisalps/projects/2
- [x] Actively manage work by tracking issues on your Kanban board.
- [x] Conduct regular project meetings to assess progress and manage schedule.
- [ ] Use code formatting tool to assure uniform source code.
- [ ] Identify and use a coding convention.
- [ ] Develop in-source documentation via Doxygen.

**Testing:**
- [x] Create basic test capabilities.
- [x] Create comprehensive test capabilities.
- [ ] Create and regularly use unit testing.
- [x] Use a pull-request, code-review integration process for source changes.
- [x] Automatically monitor and report code coverage.
- [x] Use test-driven development.
- [x] Measure and track software performance.

**Product Release:**
- [x] Create a unique and traceable release of your software product.
https://github.com/swisalps/Group_Work_General/tree/FinalProductBranch
- [ ] Make a citable version (with DOI) of your code and make it available on Zenodo or Figshare.
- [ ] Generate user and developer documentation.
- [x] Create product branding, e.g. logo family, catchphrase, product description.
