### ISSUE TITLE
Ian Bush: Initiation Checklist

### ISSUE THREAD

**Issue by IBUSH001** [swisalps/Issues#9]
- [x] Contact information will be given to the team for organization. This includes phone number, github address, and email address (we should know their name already)
- [x] New member will be added to the group message, as well as the Git organization.
- [x] The new member will be briefed on current progress and their assignment within the project by departing member.
- [ ] New members are to share their strengths and weaknesses and are assigned work accordingly.
- [x] New members will review c++ language to refresh their memory 
- [x] New members must review the SwisAples [team policies](https://github.com/swisalps/Issues/blob/master/Team%20Policy.md)
- [x] A new member will review the project material prior to their first meeting and ask questions to clear up any confusion they have
